// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT6hwQh7V2rrKXygCaUli-eoNaWDTwA8U',
    appId: '1:157150601297:web:d1e5b20e6acabb4208d870',
    messagingSenderId: '157150601297',
    projectId: 'solve-it-gdsc',
    authDomain: 'solve-it-gdsc.firebaseapp.com',
    storageBucket: 'solve-it-gdsc.appspot.com',
    measurementId: 'G-HT69W3Y6PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX7w9tOwsqLNpUNEfN1NxQdUoAxalLThM',
    appId: '1:157150601297:android:a762bb56977f216a08d870',
    messagingSenderId: '157150601297',
    projectId: 'solve-it-gdsc',
    storageBucket: 'solve-it-gdsc.appspot.com',
  );
}
